WEBSITE_APP_HOST = '127.0.0.1'
WEBSTIE_APP_PORT = '8086'

WEBSITE_APP_ROOT_URL = '%s:%s' % (WEBSITE_APP_HOST, WEBSTIE_APP_PORT)
STATIC_ROOT_URL = 'static'

IN_DEV_SERVER = True

DB_NAME = 'comments.db'